import {
  CODEX_DUMMY_KEY,
  CODEX_PROXY_BASE_URL,
  CODEX_PROXY_PORT,
  CODEX_PROXY_URL,
  MANAGED_ENV_END,
  MANAGED_ENV_START,
} from '@codex-proxy/provider-core';

export const CT_CLI_NAME = 'ct';

export const CODEX_PORT = CODEX_PROXY_PORT;
export const CODEX_BASE_URL = CODEX_PROXY_BASE_URL;
export const CODEX_PROXY_ENDPOINT = CODEX_PROXY_URL;
export const CODEX_DUMMY_KEY_VALUE = CODEX_DUMMY_KEY;
export const BUILTIN_ANTHROPIC_PROVIDER_NAME = 'anthropic';
export const LEGACY_DIRECT_PROVIDER_NAME = 'direct';

export const ZSHRC_MANAGED_ENV_START = MANAGED_ENV_START;
export const ZSHRC_MANAGED_ENV_END = MANAGED_ENV_END;

export const MANAGED_BASE_URL_VARS = [
  'ANTHROPIC_BASE_URL',
  'ANTHROPIC_API_URL',
  'ANTHROPIC_API_BASE',
  'OPENAI_API_BASE',
] as const;

export const MANAGED_KEY_VARS = ['ANTHROPIC_API_KEY', 'ANTHROPIC_AUTH_TOKEN'] as const;
